# Site wide configuration

title: "Desolate Runner"
description: "Worth it in the long run"
logo: # 120x120 px default image used for Twitter summary card
teaser: hero-img-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: "http://desolaterunner.com" # comment out when developing locally
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
feed:
  path: atom.xml
permalink: /404.html
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Tobias Johansson
  email: info@desolaterunner.com
  twitter:
  instagram: desolaterunner
  google:
    ad-client:
    ad-slot:
  bio: "A runner based in Stockholm, Sweden"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: desolaterunner

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@desolaterunner.com
  facebook:
  flickr:
  github:
  instagram: desolaterunner
  linkedin:
  pinterest:
  rss: RSS
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
