# Site wide configuration

title: "Tobias Johansson"
description: "Mountain lemmel, wordsmith and maker of visual things."
logo: # 120x120 px default image used for Twitter summary card
teaser: hero-img-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en_US
url: "https://desolaterunner.com" # comment out when developing locally
# baseurl: /

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /journal/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
feed:
  path: atom.xml
paginate: 9
paginate_path: "/journal/page:num/"
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Compress settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [head]

#Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://desolaterunner.com'
  relativeLinks: 'http://desolaterunner.com/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: "true"
          options:
            - name: "Fjällräven Classic"
              value: Fjällräven Classic
            - name: "Swedish Alpine Ultra"
              value: Swedish Alpine Ultra
            - name: "Ursvik Ultra"
              value: Ursvik Ultra
            - name: "race report"
              value: race report
            - name: "running"
              value: running
            - name: "ultra"
              value: ultra
      - name: "introduction"
        field:
          element: "textarea"
          label: "Introduction"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
      - name: "image"
        field:
          element: "textarea"
          label: "Image"
          value: |
            feature:
            teaser:
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "modified"
        field:
          element: "text"
          label: "Modified"
          value:
      - name: "ads"
        field:
          element: "checkbox"
          label: "Show ads"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
    _posts/race-reports:
      - name: "categories"
        field:
          element: "hidden"
          value: "race-reports"
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: "true"
          options:
            - name: "Fjällräven Classic"
              value: Fjällräven Classic
            - name: "Swedish Alpine Ultra"
              value: Swedish Alpine Ultra
            - name: "Ursvik Ultra"
              value: Ursvik Ultra
            - name: "race report"
              value: race report
            - name: "running"
              value: running
            - name: "ultra"
              value: ultra
      - name: "introduction"
        field:
          element: "textarea"
          label: "Introduction"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
      - name: "image"
        field:
          element: "textarea"
          label: "Image"
          value: |
            feature:
            teaser:
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "modified"
        field:
          element: "text"
          label: "Modified"
          value:
      - name: "ads"
        field:
          element: "checkbox"
          label: "Show ads"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true

#Facebook Sharing
facebook_app_id: 299865293700498

# Site owner
owner:
  name: Tobias Johansson
  email: info@desolaterunner.com
  twitter:
  instagram: desolaterunner
  facebook: desolaterunner
  google:
    ad-client: ca-pub-7422617776453761
    ad-slot: 1223360338
  bio: "A runner based in Stockholm, Sweden"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: desolaterunner
  location: "Stockholm, Sweden"

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: mail@tobiasjohansson.se
  facebook:
  flickr:
  github:
  instagram: tbs.johansson
  linkedin:
  pinterest:
  rss: RSS
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCVVU6ccjz0umc-0BepWv4og
  strava: athletes/9959817

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
